### ISSUE TITLE
how to make sub-topics?

### ISSUE THREAD

**Issue by iShift** [HelloZeroNet/ZeroTalk#11]
Like zero search http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topics:5_1PNyuY1iZqXBpft4ArouqcnE4pNRGYij5i/ZeroSearch+bit+sub+topic

**Comment by HelloZeroNet** [comment]
You have to edit your account's data.json and add type: "group" to the topic you want to turn into a group. eg.:

```
...
    {
      "body": "Articles about Bitcoin, Torrent and Peer To Peer networks", 
      "added": 1436262090, 
      "type": "group", 
      "topic_id": 1, 
      "title": "P2P news flow"
    }, 
...
```

http://127.0.0.1:43110/Talk.ZeroNetwork.bit/data/users/1KbV1e1u6P6AsY8XNBydgtbtN8iSB5WMyG/data.json

**Comment by iShift** [comment]
hmm looks like bug, all users can make groups?

**Comment by HelloZeroNet** [comment]
Sure, why not, if you dont like it you can delete any time

**Comment by iShift** [comment]
hm, you say that i can delete topic belong to another zero user?

**Comment by HelloZeroNet** [comment]
Yes, the site owner able to delete/modify anything

**Comment by iShift** [comment]
And how i can publish this change ?

**Comment by HelloZeroNet** [comment]
Using the sidebar change the `content.json` to `data/users/useraddress/content.json` then sign/publish (there was a bug related to this, so updating to latest rev is recommended)
