### ISSUE TITLE
Warning messages if you try to upvote without being logged in 

### ISSUE THREAD

**Issue by David-Leudolph** [HelloZeroNet/ZeroTalk#14]
If a user who isn't logged in or doesn't have a zeroid tries to upvote something, the message appears "Please, choose your account before upvoting". But it doesn't say how to do it. This might be a problem for new users.

**Comment by HelloZeroNet** [comment]
Fixed https://github.com/HelloZeroNet/ZeroTalk/commit/9cfc1975e0fb948c37afb2ccaf5c8a99c9db1db7
