### ISSUE TITLE
Zero Talk, markdown syntax does not support image display, we need to correct that

### ISSUE THREAD

**Issue by fanytest** [HelloZeroNet/ZeroTalk#16]
正常语法是这样的

> `![Screenshot](https://i.imgur.com/H60OAHY.png)`

正常显示是这样的
![Screenshot](https://i.imgur.com/H60OAHY.png)
然后ZeroTalk就变成了这样
`![Screenshot](https://i.imgur.com/H60OAHY.png)`

**Comment by HelloZeroNet** [comment]
This is intentionally: https://github.com/HelloZeroNet/ZeroTalk/blob/master/js/utils/Text.coffee#L1

you can enable it if you want images in your forum, but it's reduces privacy, because anyone can include image from clearnet and log users ip
