### ISSUE TITLE
Sort 0list by upvotes

### ISSUE THREAD

**Issue by cellininicholas** [HelloZeroNet/ZeroTalk#21]
As seen here:
https://github.com/HelloZeroNet/ZeroNet/issues/563

**Comment by fiskr** [comment]
I don't understand - is 0list a ZeroTalk zite? How is it managed, and what makes this a ZeroTalk issue?

**Comment by HelloZeroNet** [comment]
Yeah it's fork of it, but unfortunetly it's not my site, so I can't modify it.

**Comment by fiskr** [comment]
@cellininicholas and @HelloZeroNet is there a repository for the 0List zite? We should make sure this is logged there.
