### ISSUE TITLE
"Start new topic" button goes down in mobile devices.

### ISSUE THREAD

**Issue by ysc3839** [HelloZeroNet/ZeroTalk#30]
I don't know how to fix it. So tell you to fix it.
![snipaste20161126_235150](https://cloud.githubusercontent.com/assets/12028138/20641479/840af6d2-b433-11e6-80e1-6c8eee2f79ec.png)

**Comment by fiskr** [comment]
Not sure what you are asking for. Do you want the new topic button in a different location? It does look pretty bad - but I am not even sure we support mobile explicitly. (We should, though - I am just not sure anyone is running ZeroNet on mobile yet).

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it should be better now!
