### ISSUE TITLE
English pluralization of "comment" is wrong

### ISSUE THREAD

**Issue by SilverWingedSeraph** [HelloZeroNet/ZeroTalk#37]
When a thread has 0 comments the text correctly reads "0 comments", but for 2, 3, ... n comments it is incorrectly "n comment".

**Comment by fiskr** [comment]
I think I can solve this.

**Comment by fiskr** [comment]
Ignore the first two - just realized I can't do all my dev in my forked master if I want to make separate pull requests for #37 and #39
