### ISSUE TITLE
Allow using no sticky topics

### ISSUE THREAD

**Issue by imachug** [HelloZeroNet/ZeroTalk#48]
**Steps to Reproduce:**
1. Clone ZeroTalk
2. Replace `"topic_sticky_uris": [...]` with `"topic_sticky_uris": []` in `content.json`
3. Sign `content.json`
4. Update page

**Actual Results:**
The following error appears in Developer Console:
```
TypeError: topics.sort is not a function (js/all.js:1404)
```
```javascript
topics.sort(function(a, b) {
````

**Expected Results:**
The page shows with no sticky topics in the top.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed: https://github.com/HelloZeroNet/ZeroTalk/commit/12a35e021a400da27a8e660fc47af717e8cfc3c3#diff-c3fbc0d1e0ceadc61cb6ecbb0cd27be7
