### ISSUE TITLE
[Feature] Automaticaly subscribe topic starter to Follow his topic

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroTalk#56]
Hello, sometimes when i create new topic at ZeroTalk, i forget to click "Follow in Newsfeed". It may be useful if system automatically subscribe me once i create a topic?

I am not a programmer but i guess there is needed some tiny edit in [js/all.js](https://github.com/HelloZeroNet/ZeroTalk/blob/master/js/all.js) if anyone know and have a minute, please kindly share how to achieve that or even implement it right into ZeroTalk.

**Comment by slrslr** [comment]
one year later, hoping this can be added so users are more involved and do not miss replies to their topics

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme

**Comment by HelloZeroNet** [comment]
Great suggestion, added: https://github.com/HelloZeroNet/ZeroTalk/commit/17e3eda44ec8ba2cb5c04b964ebd899e2a744df2 :)
