### ISSUE TITLE
Please add permalink of each comment so people can link to a comments

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroTalk#61]
Hello,

it is around 4th time i was wanting to reference a ZeroTalk comment from other zite or other ZeroTalk topic and i can not find the link of particular comment. Please can you add a hyperlink under date of each zerotalk comment and the hyperlink will be a permanent link to the post? So i can right click date and copy the link. Or other simple, space savvy way offer the link to the comment?

Update: there already is a menu at the end of each comment (hard to be seen three dots), so it is other possible location for permalink a maybe.

**Comment by HelloZeroNet** [comment]
Added in latest changeset
