### ISSUE TITLE
Every site owner! Plz make page title out of its subject!

### ISSUE THREAD

**Issue by leftside2** [HelloZeroNet/ZeroTalk#72]
Not just "ZeroTalk - ZeroNet" though every page/article has its own subject/title. 

I used to open more than 500 tabs per browser instance (I used to use 3 instances), 
Every web sites provide distinguishable tab title (or window title), but why not with ZeroNet?????

It's really pain in the neck when I need to find a certain page among 500 tabs. ;(

**Comment by slrslr** [comment]
Millchan has this https://gitgud.io/mcdev/Millchan/blob/master/js/millchan/viewer.js#L369

**Comment by DaniellMesquita** [comment]
Millchan is which kind of CMS?

**Comment by HelloZeroNet** [comment]
Added: https://github.com/HelloZeroNet/ZeroTalk/commit/3793a809b88f3998929bbdb746caa9e42c5b31c5

**Comment by leftside2** [comment]
@HelloZeroNet, Thanks a lot!!!!!!! Excellent! :)

**Comment by slrslr** [comment]
Very nice, i can now use Firefox address bar to easily find ZeroTalk topic i opened in history just by typing phrase it has in its subject (topic title).

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme 
But that yet needs an favicon, in case of using Chrome with lots of tabs.
Reference: https://github.com/HelloZeroNet/ZeroTalk/pull/75
