### ISSUE TITLE
[Proposal]: Downvote button

### ISSUE THREAD

**Issue by christopherturner** [HelloZeroNet/ZeroTalk#9]
I think that a downvote button (with similar functionality to reddit's) would be a great way to deal with spam on ZeroTalk, etc.

**Comment by Angristan** [comment]
Agreed. It would be usefull to show that we do not support racism and anti-semitism.

**Comment by wpstudio** [comment]
I know this has been said in other issue proposals but I'm against a downvote button that would have any ramifications to the "censorship" aspect of Zeronet(talk).  I think a better approach is a "HIDE button" that simply blacklists a certain userID from appearing on that individual's version of their localhost sync'd site.  No one gets censored globally.  But if a user "abuses" the system most people will "locally" blacklist that user and no one will see him/her saying anything.  This prevents downvote gangs from getting together and booting out people who got on the wrong side of an argument.

**Comment by christopherturner** [comment]
That's a good idea, but just to clarify, I wasn't suggesting censorship.  I'd simply like to solve the issue of spam, racism, and antisemitism.

@wpstudio +1 to your idea.

**Comment by Mujaja** [comment]
I agree with @wpstudio's idea. The list of what users should be hidden could be stored in the user's users.json so that it can be used in different sites.
```
"hidden_users": "bad@zeroid.bit, spammer@zeroid.bit",
```

The downvote on reddit does a lot of harm. A "community solution" could be the **possibility** to import someone else's block list. This way you can hide what your trusted peer considers hide-worthy.

**Comment by Mrkebubun** [comment]
HIDE button like wpstudio say probobly is a good idea.

**Comment by HelloZeroNet** [comment]
https://github.com/HelloZeroNet/ZeroNet/issues/388
